config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :suppliers, :sales
  resources :items do
  	resources :item_images
  end

  root "items#index"
end

app/models/item.rb
class Item < ActiveRecord::Base
	belongs_to :item_type
	belongs_to :supplier
	has_many :sale_details
	has_many :sales, through: :sale_details
	has_many :item_images

	validates :name, :supplier_id, :item_type_id, presence: true
	accepts_nested_attributes_for :item_images
end

app/models/item_image.rb
class ItemImage < ActiveRecord::Base
	belongs_to :item

	validates :image_url, :item, presence: true
end

app/models/item_type.rb
class ItemType < ActiveRecord::Base
	has_many :items

	validates :name, presence: true
end

app/models/sale.rb
class Sale < ActiveRecord::Base
	belongs_to :supplier
	has_many :sale_details
	has_many :items, through: :sale_details
end

app/models/sale_detail.rb
class SaleDetail < ActiveRecord::Base
	belongs_to :item
	belongs_to :sale

	validates :sale, :item, presence: true
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
	has_many :items
	has_many :sales
	has_many :users

	validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	belongs_to :supplier

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/item_images_controller.rb
class ItemImagesController < ApplicationController
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]
	before_action :set_item, only: [:show, :edit, :update, :destroy]
	before_action :set_s3_direct_post, only: [:new, :edit, :create, :update]

	def index
		@items = Item.all
	end

	def new
		@item = Item.new
	end

	def create
		
	end

	private
		def set_item
			@item = Item.find(params[:id])
		end

		def item_params
			params.require(:items).permit(:name, :description, :original_price, :supplier_id, :item_type_id)
		end

	    def set_s3_direct_post
	      @s3_direct_post = S3_BUCKET.presigned_post(key: "uploads/#{SecureRandom.uuid}/${filename}", success_action_status: '201', acl: 'public-read')
	    end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/item_images_helper.rb
module ItemImagesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/views/items/_form.html.erb
<%= form_for(@item, html: { class: 'directUpload', data: { 'form-data' => (@s3_direct_post.fields), 'url' =>
@s3_direct_post.url, 'host' => URI.parse(@s3_direct_post.url).host } }) do |f| %>   

	<% if @item.errors.any? %>     
	  <div id="error_explanation">       
	    <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>
	        <ul>
	        <% @item.errors.full_messages.each do |message| %>
	          <li><%= message %></li>
	        <% end %>
	        </ul>
	      </div>
	<% end %>

	  <div class="field">
	    <%= f.label :name %><br>
	    <%= f.text_field :name %>
	  </div>
	  <div class="field">
	    <%= f.label :description %><br>
	    <%= f.text_field :description %>
	  </div>
	  <div class="field">
	    <%= f.label :original_price %><br>
	    <%= f.text_field :original_price %>
	  </div>
	  <div class="field">
	    <%= f.label :supplier %><br>
	    <%= f.collection_select(:supplier_id, Supplier.all, :id, :name, prompt: true) %>
	  </div>
	  <div class="field">
	    <%= f.label :item_type %><br>
	    <%= f.collection_select(:item_type_id, ItemType.all, :id, :name, prompt: true) %>
	  </div>

<% end %>

app/views/items/index.html.erb
<h1>Items for Sale</h1>

app/views/items/new.html.erb
<h1>Add new item</h1>
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Salestore</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if user_signed_in? %>
	<%= link_to "New Item", new_item_path %>
	<%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
<% else %>
	<%= link_to "Sign Up", new_user_registration_path %>
	<%= link_to "Sign In", new_user_session_path %>
<% end %>

<%= yield %>

</body>
</html>